name: 'arch-go'

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  Arch-Go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.15'
#      - name: Install Arch-Go
#        run: go get -u github.com/fdaines/arch-go
#      - name: Run Arch-Go
#        run: arch-go

