name: 'mutation'

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  Mutation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.15'
      - name: Install Go Mutesting
        run: go get -u github.com/zimmski/go-mutesting
      - name: Run Go Mutesting
        run: go-mutesting ./...


