name: 'mutation'

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  Mutation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.15'
      - uses: rescDev/go-mutesting-action@v1.0.0
        with:
          targets: ./...
          disabled: structinit/remove
#          blacklist-file: gomutest.blacklist
          output: verbose


