name: 'testing-pipeline'

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  Unit-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.15'
      - name: Run Unit-Tests
        run: go test -cover ./...
  Mutation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.15'
      - uses: rescDev/go-mutesting-action@v1.0.0
        with:
          targets: ./...
          disabled: structinit/remove
#          blacklist-file: gomutest.blacklist
          output: verbose
  Arch-Go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.15'
      - name: Install Arch-Go
        run: go get -u github.com/fdaines/arch-go
      - name: Run Arch-Go
        run: arch-go


